### PR TITLE
feat: enable GPU acceleration through CUDA using cuBLAS

### PR DESCRIPTION
**Pull request by troyedwardsjr**
https://github.com/ggerganov/llama.cpp#cublas

Gated by Rust feature.

### CODE REVIEW

**Review by Juzov — APPROVED** [review]
LGTM

**Comment by Juzov** [comment]
Can you please check the error

**Comment by troyedwardsjr** [comment]
> Can you please check the error

@Juzov Whoops! Should be good now.

**Comment by troyedwardsjr** [comment]
```
$ cargo build --example stream
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
```

**Comment by Juzov** [comment]
Format the code and we should be golden :)

**Comment by troyedwardsjr** [comment]
> Format the code and we should be golden :)

@Juzov Done. :)

**Pull request merged**
