### PR TITLE
Chore: cargo clippy

### PR DESCRIPTION
**Pull request by AnthonyMichaelTDM**
This PR fixes various clippy lints

I first ran cargo clippy --fix, then fixed remaining lints manually

this is both non-essential and should be reviewed before merging, because it changes a bunch of files and could cause conflicts with stuff other people are working on

### CODE REVIEW

**Review by williamhogman — APPROVED** [review]

**Comment by williamhogman** [comment]
Looks like someone forgot to run cargo fmt ;)

**Comment by AnthonyMichaelTDM** [comment]
> Looks like someone forgot to run cargo fmt ;)

yeah haha

**Comment by AnthonyMichaelTDM** [comment]
should probably make a git hook for that ...

**Comment by williamhogman** [comment]
> should probably make a git hook for that ...

Would love to have something along those lines

**Comment by AnthonyMichaelTDM** [comment]
adding a file named `pre-commit` to your .git/hooks/ directory, with the following content:
```
cargo fmt --all -- --check
```
then making it executable with `chmod +x .git/hooks/pre-commit` 

does the trick

**Comment by williamhogman** [comment]
> adding a file named `pre-commit` to your .git/hooks/ directory, with the following content:
> 
> ```
> cargo fmt --all -- --check
> ```
> 
> then making it executable with `chmod +x .git/hooks/pre-commit`
> 
> does the trick

Right but usually you'd want a wrapper such as pre-commit or similar :)

**Pull request merged**
