### PR TITLE
Add gemma.cpp bindings / llm-chain-gemma.

### PR DESCRIPTION
**Pull request by jmuk**

### CODE REVIEW

**Review by williamhogman — APPROVED** [review]

**Comment by williamhogman** [comment]
Thanks for that :) seems the CI itself passe

**Comment by williamhogman** [comment]
Other than windows

**Comment by jmuk** [comment]
Sigh, sorry about that.  I made one more change, I hope it fixes the windows build...

**Comment by williamhogman** [comment]
Still some weird issue with windows @jmuk

**Comment by jmuk** [comment]
Looks like an error on compiling C++ code, possibly due to a macro defined in a standard Windows header file?  (cf. https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included).  I checked gemma.cpp repository but seemingly their CI includes windows and it looks fine.
I'll check how it's resolved there and ports their resolution here -- which is (I hope) simply updating gemme.cpp version referred in the .gitmodule file.

**Comment by jmuk** [comment]
I checked gemma.cpp and recent version has `NOMINMAX` macro for windows, which should resolve the build issue.  I updated the version so I think it won't get trapped by that error.

However the gemma.cpp interface has changed very significantly.  I rebuilt bindings.cc and others to catch up with that and confirmed it's built and works successfully on my local macbook.  Sorry for the troubles, but please run the CI checks again!

**Comment by jmuk** [comment]
Sigh, I just found that gemma.cpp does not support MSBuild / MSVC, it only supports clang-cl for now.  I gave up on Windows build; with the new patch, it should pass the build on Windows and CI should pass, but on Windows it will raise `ExecutorCreationError` on Windows.

Please run the CI again!

**Comment by jmuk** [comment]
The CI seems retried yesterday but that was on an older revision?  Could someone run the CI on the latest one https://github.com/sobelio/llm-chain/pull/281/commits/42932846f87586cfdfd1aea7cdf63ca1d662d8a9

**Comment by williamhogman** [comment]
All good. Seems like it is ready to merge. Let me know you want me to go ahead and package it

**Comment by jmuk** [comment]
Yay!  Please go ahead anytime you can.

**Pull request merged**
