### PR TITLE
Update to support the new llama.cpp and fix executor bug

### PR DESCRIPTION
**Pull request by cometyang**
update code for https://github.com/ggerganov/llama.cpp/pull/1509  and fix executor.

### CODE REVIEW

**Comment by williamhogman** [comment]
Hey could you run 
`cargo fmt` so it passes the lint :)

**Review by williamhogman — APPROVED** [review]
LGTM

**Comment by cometyang** [comment]
i run "cargo fmt", now it should have no format issue.

**Comment by williamhogman** [comment]
Still some problem with the example but will merge and fix in main instead.

**Pull request merged**
