### PR TITLE
Added the text associated with the vector to the qdrant payload.

### PR DESCRIPTION
**Pull request by RalfNorthman**
I thought it would be useful to save the original text (as a payload field) along with the embedding vector in qdrant. Otherwise you have to associate the original text with the uuid some other way (save it in another database?). With this PR we can get the associated text directly from the vector search response.

We have some unseemly `clone`-calls, but since both `async-openai` and `qdrant_client` wants to take ownership of the input, I don't think it can be helped.

### CODE REVIEW

**Comment by Pablo1785** [comment]
Hey, good catch, I didn't notice that I forgot to include the original text

I added it along with ability to specify payload keys as part of https://github.com/sobelio/llm-chain/pull/59

**Comment by williamhogman** [comment]
Good work both, would be great if you guys could figure out a way to merge your PRs into one :) 

Regarding unnecessary copies our current policy is rather a few clones too many and then optimise as we go. Personally I often catch myself think how do I optimise away this `clone` rather than asking wait a minute how often is this code called 😂

**Comment by williamhogman** [comment]
Maybe @Pablo1785 can do a git pull from @RalfNorthman 's branch :)

**Comment by Pablo1785** [comment]
> Maybe @Pablo1785 can do a git pull from @RalfNorthman 's branch :)

Sure, I'll rebase

**Comment by Pablo1785** [comment]
> > Maybe @Pablo1785 can do a git pull from @RalfNorthman 's branch :)
> 
> Sure, I'll rebase

Done

**Comment by RalfNorthman** [comment]
Okay, nice! I'm closing this, then. :-)

**Comment by RalfNorthman** [comment]
I misunderstood. Opening again.

**Comment by williamhogman** [comment]
@RalfNorthman your change made it in right? :)

**Comment by RalfNorthman** [comment]
I was to quick on the draw closing my PR. Therefore I think we got the angry red **closed** on it , instead of the purple. I looked at the file in main and it looks like my changes made it in. It's all good.

**Comment by williamhogman** [comment]
Ah don't think we can get the purple, but no worries :)

**Pull request closed without merging**
